const produkte = [
    { name: 'Hochzeitspakete ab', preis: '150' },
    { name: 'Waschen Bonacure', preis: '3,70' },
    { name: 'Waschen Blond Me', preis: '7' },
    { name: 'Haarschnitt', preis: '28,70' },
    { name: 'Fönfrisur kurze Haare', preis: '15,60' },
    { name: 'Fönfrisur lange Haare', preis: '32,40' },
    { name: 'Glätten/Locken', preis: '31,20' },
    { name: 'Stecken einfach', preis: '33,70' },
    { name: 'Stecken Aufwendig', preis: '40,30' },
    { name: 'Blondierung Blond Me', preis: '34' },
    { name: 'Blondierung Überlänge', preis: '7' },
    { name: 'Meschen Oberkopf', preis: '39,20' },
    { name: 'Meschen ganzer Kopf', preis: '78,40' },
    { name: 'Strähnen einzeln', preis: '6,90' },
    { name: 'Farbe/Tönung', preis: '39,20' },
    { name: 'Farbe/Tönung überlänge', preis: '11' },
    { name: 'Pflege Bonacure', preis: '5,50' },
    { name: 'Pflege Blond Me', preis: '6,20' },
    { name: 'Detox Behandlung', preis: '9,30' },
    { name: 'Dauerwelle', preis: '53,60' },
    { name: 'Herrenservice', preis: '28,70' },
    { name: 'Kinderservice ab 6 Jahren', preis: '14,50' },
    { name: 'Maniküre', preis: '15,10' },
    { name: 'Lackierung', preis: '8,60' },
    { name: 'Augenbrauenfärben', preis: '6' },
    { name: 'Zupfen', preis: '7' },
    { name: 'Wimpernfärben', preis: '8' },
    { name: 'Tages Make-up', preis: '26' },
    { name: 'Abend/Event Make-up', preis: '55' },
    { name: 'Make-up Beratung', preis: '30' },
]

